/********************************************************************************
** Form generated from reading UI file 'parameters2.ui'
**
** Created by: Qt User Interface Compiler version 5.15.18
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PARAMETERS2_H
#define UI_PARAMETERS2_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include "improvedlineedit.h"

QT_BEGIN_NAMESPACE

class Ui_Parameters2
{
public:
    QTabWidget *tabWidget;
    QWidget *tab;
    QComboBox *model;
    QLabel *label_6;
    QLabel *label_22;
    ImprovedLineEdit *velocityOrder;
    QGroupBox *groupBox_8;
    ImprovedLineEdit *dm;
    ImprovedLineEdit *dx;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_28;
    QLabel *dt;
    QGroupBox *groupBox_14;
    QLabel *label_27;
    QLabel *label_13;
    QComboBox *material;
    ImprovedLineEdit *epsilon;
    QLabel *label_32;
    ImprovedLineEdit *kinematicViscosity;
    QLabel *label_40;
    QComboBox *fluidOrder;
    QWidget *tab_2;
    QGroupBox *groupBox;
    QPushButton *updateInitial;
    QLineEdit *minZ;
    QLabel *label_11;
    QLineEdit *maxY;
    QLineEdit *maxX;
    QLabel *label_8;
    QLineEdit *maxZ;
    QLineEdit *density2;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_10;
    QLabel *label_7;
    QLineEdit *minX;
    QLineEdit *minY;
    QLineEdit *density1;
    QLabel *label_9;
    QLabel *label_12;
    QPushButton *updateConstant;
    QPushButton *regionAll;
    QPushButton *regionCenter;
    QGroupBox *groupBox_3;
    QLabel *label_16;
    ImprovedLineEdit *minP0;
    QLabel *label_17;
    ImprovedLineEdit *maxP0;
    QGroupBox *groupBox_17;
    QPushButton *loadMaskPorousMedia;
    QLabel *label_62;
    QComboBox *colorComponentPorous;
    QLabel *label_63;
    QLineEdit *averageValuePorous;
    QLabel *label_64;
    QLineEdit *variationPorous;
    QWidget *tab_3;
    QCheckBox *periodicBoundaries;
    QLabel *label_33;
    QComboBox *outletStrategy;
    QGroupBox *groupBox_10;
    ImprovedLineEdit *thermal1;
    QLabel *label_34;
    ImprovedLineEdit *thermalGravity;
    QLabel *label_36;
    QLabel *label_38;
    ImprovedLineEdit *thermalExpansion;
    QLabel *label_35;
    QComboBox *thermalIndex;
    QGroupBox *groupBox_11;
    ImprovedLineEdit *sourceVelocity;
    QLabel *label_39;
    QComboBox *inletOrder;
    QLabel *label_43;
    QLabel *label_48;
    ImprovedLineEdit *sourceVelocity2;
    QLabel *label_54;
    ImprovedLineEdit *sourcePressure;
    QLabel *label_77;
    QLineEdit *inletFormula;
    QGroupBox *groupBox_12;
    QLabel *label_44;
    ImprovedLineEdit *movingVelocity;
    QLabel *label_46;
    ImprovedLineEdit *movingVelocityY;
    ImprovedLineEdit *movingVelocity2;
    ImprovedLineEdit *movingVelocityY2;
    QLabel *label_41;
    QLabel *label_42;
    QWidget *tab_4;
    QGroupBox *groupBox_2;
    QLabel *label;
    ImprovedLineEdit *mpG;
    ImprovedLineEdit *mpPsi0;
    ImprovedLineEdit *mpP0;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_18;
    ImprovedLineEdit *mpGads;
    QGroupBox *groupBox_4;
    QComboBox *mcQuantity;
    QLabel *label_4;
    QLabel *label_5;
    ImprovedLineEdit *mcG;
    QLabel *label_19;
    ImprovedLineEdit *mcGads;
    QLabel *label_20;
    ImprovedLineEdit *mcGads2;
    QLabel *label_21;
    QComboBox *mcType;
    QLabel *label_76;
    ImprovedLineEdit *mcDensityRatio;
    QWidget *tab_5;
    QCheckBox *activateKorner;
    QGroupBox *groupBox_19;
    QLabel *label_65;
    ImprovedLineEdit *ebmPower;
    QLabel *label_66;
    ImprovedLineEdit *ebmStdDev;
    QLabel *label_67;
    QLabel *label_69;
    QLabel *label_70;
    ImprovedLineEdit *ebmStartX;
    ImprovedLineEdit *ebmVelocity;
    ImprovedLineEdit *ebmTimesteps;
    ImprovedLineEdit *ebmAbsorptionCoefficient;
    QLabel *label_71;
    QGroupBox *groupBox_20;
    QLabel *label_68;
    ImprovedLineEdit *kornerLiquidTau;
    QLabel *label_72;
    ImprovedLineEdit *kornerSolidTau;
    ImprovedLineEdit *kornerGasTau;
    QLabel *label_73;
    ImprovedLineEdit *kornerSolidEnergy;
    QLabel *label_74;
    ImprovedLineEdit *kornerLiquidEnergy;
    QLabel *label_75;
    QWidget *tab_7;
    QLabel *label_55;
    ImprovedLineEdit *nanoFraction;
    ImprovedLineEdit *nanoDensity;
    QLabel *label_56;
    QLabel *label_57;
    ImprovedLineEdit *nanoThermalExpansion;
    ImprovedLineEdit *nanoThermalConductivity;
    QLabel *label_58;
    QLabel *label_59;
    ImprovedLineEdit *nanoHeatCapacitance;
    QLabel *label_60;
    QComboBox *nanoparticles;
    QWidget *tab_6;
    QGroupBox *groupBox_5;
    QCheckBox *gravityEnable;
    ImprovedLineEdit *gravity;
    QGroupBox *groupBox_6;
    QLabel *label_23;
    ImprovedLineEdit *shallowG;
    QLabel *label_24;
    ImprovedLineEdit *shallowNB;
    QGroupBox *groupBox_7;
    ImprovedLineEdit *porousSolidDensity;
    QLabel *label_25;
    QLabel *label_61;
    ImprovedLineEdit *porousVariation;
    QGroupBox *groupBox_9;
    QLabel *label_31;
    ImprovedLineEdit *depositionRate;
    QGroupBox *groupBox_13;
    QLabel *label_47;
    ImprovedLineEdit *slipCoefficient;
    QGroupBox *groupBox_15;
    QLabel *label_37;
    ImprovedLineEdit *anodeCathodeFactor;
    QGroupBox *groupBox_16;
    QLabel *label_45;
    ImprovedLineEdit *externalForceStrengthX;
    QLabel *label_49;
    ImprovedLineEdit *externalForceMinX;
    QLabel *label_50;
    ImprovedLineEdit *externalForceMaxX;
    QLabel *label_51;
    ImprovedLineEdit *externalForceMinY;
    QLabel *label_52;
    ImprovedLineEdit *externalForceMaxY;
    ImprovedLineEdit *externalForceStrengthY;
    ImprovedLineEdit *externalForcePeriod;
    QLabel *label_53;
    QGroupBox *groupBox_18;
    QCheckBox *entropic;
    QLabel *label_26;
    ImprovedLineEdit *smagorinsky;

    void setupUi(QDialog *Parameters2)
    {
        if (Parameters2->objectName().isEmpty())
            Parameters2->setObjectName(QString::fromUtf8("Parameters2"));
        Parameters2->resize(521, 352);
        tabWidget = new QTabWidget(Parameters2);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 10, 501, 331));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        model = new QComboBox(tab);
        model->addItem(QString());
        model->addItem(QString());
        model->addItem(QString());
        model->addItem(QString());
        model->setObjectName(QString::fromUtf8("model"));
        model->setEnabled(true);
        model->setGeometry(QRect(10, 30, 111, 22));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 10, 61, 13));
        label_22 = new QLabel(tab);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(140, 10, 81, 16));
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        velocityOrder = new ImprovedLineEdit(tab);
        velocityOrder->setObjectName(QString::fromUtf8("velocityOrder"));
        velocityOrder->setGeometry(QRect(160, 30, 61, 20));
        groupBox_8 = new QGroupBox(tab);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(10, 70, 221, 71));
        dm = new ImprovedLineEdit(groupBox_8);
        dm->setObjectName(QString::fromUtf8("dm"));
        dm->setGeometry(QRect(150, 40, 61, 20));
        dm->setReadOnly(false);
        dx = new ImprovedLineEdit(groupBox_8);
        dx->setObjectName(QString::fromUtf8("dx"));
        dx->setGeometry(QRect(10, 40, 61, 22));
        label_29 = new QLabel(groupBox_8);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 20, 61, 16));
        label_30 = new QLabel(groupBox_8);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(80, 20, 46, 13));
        label_28 = new QLabel(groupBox_8);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(150, 20, 111, 16));
        dt = new QLabel(groupBox_8);
        dt->setObjectName(QString::fromUtf8("dt"));
        dt->setGeometry(QRect(80, 40, 61, 16));
        groupBox_14 = new QGroupBox(tab);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(240, 10, 221, 171));
        label_27 = new QLabel(groupBox_14);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(10, 70, 61, 16));
        label_13 = new QLabel(groupBox_14);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(80, 120, 131, 16));
        label_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        material = new QComboBox(groupBox_14);
        material->addItem(QString());
        material->addItem(QString());
        material->addItem(QString());
        material->addItem(QString());
        material->setObjectName(QString::fromUtf8("material"));
        material->setGeometry(QRect(10, 90, 201, 22));
        epsilon = new ImprovedLineEdit(groupBox_14);
        epsilon->setObjectName(QString::fromUtf8("epsilon"));
        epsilon->setGeometry(QRect(10, 140, 61, 20));
        label_32 = new QLabel(groupBox_14);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 120, 91, 16));
        kinematicViscosity = new ImprovedLineEdit(groupBox_14);
        kinematicViscosity->setObjectName(QString::fromUtf8("kinematicViscosity"));
        kinematicViscosity->setGeometry(QRect(150, 140, 61, 22));
        label_40 = new QLabel(groupBox_14);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 20, 46, 13));
        fluidOrder = new QComboBox(groupBox_14);
        fluidOrder->addItem(QString());
        fluidOrder->addItem(QString());
        fluidOrder->setObjectName(QString::fromUtf8("fluidOrder"));
        fluidOrder->setGeometry(QRect(10, 40, 201, 22));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        groupBox = new QGroupBox(tab_2);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 10, 151, 281));
        updateInitial = new QPushButton(groupBox);
        updateInitial->setObjectName(QString::fromUtf8("updateInitial"));
        updateInitial->setEnabled(true);
        updateInitial->setGeometry(QRect(10, 250, 61, 23));
        updateInitial->setAutoDefault(false);
        minZ = new QLineEdit(groupBox);
        minZ->setObjectName(QString::fromUtf8("minZ"));
        minZ->setEnabled(true);
        minZ->setGeometry(QRect(10, 170, 61, 20));
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(80, 100, 46, 13));
        maxY = new QLineEdit(groupBox);
        maxY->setObjectName(QString::fromUtf8("maxY"));
        maxY->setEnabled(true);
        maxY->setGeometry(QRect(80, 120, 61, 20));
        maxX = new QLineEdit(groupBox);
        maxX->setObjectName(QString::fromUtf8("maxX"));
        maxX->setEnabled(true);
        maxX->setGeometry(QRect(80, 70, 61, 20));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(80, 50, 46, 13));
        maxZ = new QLineEdit(groupBox);
        maxZ->setObjectName(QString::fromUtf8("maxZ"));
        maxZ->setEnabled(true);
        maxZ->setGeometry(QRect(80, 170, 61, 20));
        density2 = new QLineEdit(groupBox);
        density2->setObjectName(QString::fromUtf8("density2"));
        density2->setEnabled(true);
        density2->setGeometry(QRect(80, 220, 61, 20));
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 200, 101, 16));
        label_15 = new QLabel(groupBox);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(80, 200, 101, 16));
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 150, 46, 13));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(80, 150, 46, 13));
        minX = new QLineEdit(groupBox);
        minX->setObjectName(QString::fromUtf8("minX"));
        minX->setEnabled(true);
        minX->setGeometry(QRect(10, 70, 61, 20));
        minY = new QLineEdit(groupBox);
        minY->setObjectName(QString::fromUtf8("minY"));
        minY->setEnabled(true);
        minY->setGeometry(QRect(10, 120, 61, 20));
        density1 = new QLineEdit(groupBox);
        density1->setObjectName(QString::fromUtf8("density1"));
        density1->setEnabled(true);
        density1->setGeometry(QRect(10, 220, 61, 20));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 50, 46, 13));
        label_12 = new QLabel(groupBox);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 100, 46, 13));
        updateConstant = new QPushButton(groupBox);
        updateConstant->setObjectName(QString::fromUtf8("updateConstant"));
        updateConstant->setEnabled(true);
        updateConstant->setGeometry(QRect(80, 250, 61, 23));
        updateConstant->setAutoDefault(false);
        regionAll = new QPushButton(groupBox);
        regionAll->setObjectName(QString::fromUtf8("regionAll"));
        regionAll->setEnabled(true);
        regionAll->setGeometry(QRect(10, 20, 61, 23));
        regionAll->setAutoDefault(false);
        regionCenter = new QPushButton(groupBox);
        regionCenter->setObjectName(QString::fromUtf8("regionCenter"));
        regionCenter->setEnabled(true);
        regionCenter->setGeometry(QRect(80, 20, 61, 23));
        regionCenter->setAutoDefault(false);
        groupBox_3 = new QGroupBox(tab_2);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(170, 10, 151, 71));
        label_16 = new QLabel(groupBox_3);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(10, 20, 61, 13));
        minP0 = new ImprovedLineEdit(groupBox_3);
        minP0->setObjectName(QString::fromUtf8("minP0"));
        minP0->setGeometry(QRect(10, 40, 61, 20));
        label_17 = new QLabel(groupBox_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(80, 20, 46, 13));
        maxP0 = new ImprovedLineEdit(groupBox_3);
        maxP0->setObjectName(QString::fromUtf8("maxP0"));
        maxP0->setGeometry(QRect(80, 40, 61, 20));
        groupBox_17 = new QGroupBox(tab_2);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(170, 90, 151, 201));
        loadMaskPorousMedia = new QPushButton(groupBox_17);
        loadMaskPorousMedia->setObjectName(QString::fromUtf8("loadMaskPorousMedia"));
        loadMaskPorousMedia->setGeometry(QRect(10, 170, 131, 23));
        loadMaskPorousMedia->setAutoDefault(false);
        label_62 = new QLabel(groupBox_17);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(10, 20, 131, 16));
        colorComponentPorous = new QComboBox(groupBox_17);
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->addItem(QString());
        colorComponentPorous->setObjectName(QString::fromUtf8("colorComponentPorous"));
        colorComponentPorous->setGeometry(QRect(10, 40, 131, 22));
        label_63 = new QLabel(groupBox_17);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(10, 70, 131, 16));
        averageValuePorous = new QLineEdit(groupBox_17);
        averageValuePorous->setObjectName(QString::fromUtf8("averageValuePorous"));
        averageValuePorous->setGeometry(QRect(10, 90, 131, 20));
        label_64 = new QLabel(groupBox_17);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(10, 120, 131, 16));
        variationPorous = new QLineEdit(groupBox_17);
        variationPorous->setObjectName(QString::fromUtf8("variationPorous"));
        variationPorous->setGeometry(QRect(10, 140, 131, 20));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        periodicBoundaries = new QCheckBox(tab_3);
        periodicBoundaries->setObjectName(QString::fromUtf8("periodicBoundaries"));
        periodicBoundaries->setGeometry(QRect(10, 10, 171, 18));
        periodicBoundaries->setChecked(true);
        label_33 = new QLabel(tab_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 40, 101, 16));
        outletStrategy = new QComboBox(tab_3);
        outletStrategy->addItem(QString());
        outletStrategy->addItem(QString());
        outletStrategy->addItem(QString());
        outletStrategy->addItem(QString());
        outletStrategy->setObjectName(QString::fromUtf8("outletStrategy"));
        outletStrategy->setEnabled(true);
        outletStrategy->setGeometry(QRect(10, 60, 151, 22));
        groupBox_10 = new QGroupBox(tab_3);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(180, 10, 151, 121));
        thermal1 = new ImprovedLineEdit(groupBox_10);
        thermal1->setObjectName(QString::fromUtf8("thermal1"));
        thermal1->setGeometry(QRect(80, 90, 61, 20));
        label_34 = new QLabel(groupBox_10);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(80, 70, 61, 16));
        thermalGravity = new ImprovedLineEdit(groupBox_10);
        thermalGravity->setObjectName(QString::fromUtf8("thermalGravity"));
        thermalGravity->setGeometry(QRect(10, 40, 61, 20));
        label_36 = new QLabel(groupBox_10);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 20, 61, 16));
        label_38 = new QLabel(groupBox_10);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(80, 20, 61, 16));
        thermalExpansion = new ImprovedLineEdit(groupBox_10);
        thermalExpansion->setObjectName(QString::fromUtf8("thermalExpansion"));
        thermalExpansion->setGeometry(QRect(80, 40, 61, 20));
        label_35 = new QLabel(groupBox_10);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 70, 46, 13));
        thermalIndex = new QComboBox(groupBox_10);
        thermalIndex->addItem(QString());
        thermalIndex->addItem(QString());
        thermalIndex->addItem(QString());
        thermalIndex->setObjectName(QString::fromUtf8("thermalIndex"));
        thermalIndex->setGeometry(QRect(10, 90, 61, 22));
        groupBox_11 = new QGroupBox(tab_3);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(10, 140, 481, 71));
        sourceVelocity = new ImprovedLineEdit(groupBox_11);
        sourceVelocity->setObjectName(QString::fromUtf8("sourceVelocity"));
        sourceVelocity->setGeometry(QRect(80, 40, 61, 20));
        label_39 = new QLabel(groupBox_11);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(80, 20, 71, 16));
        inletOrder = new QComboBox(groupBox_11);
        inletOrder->addItem(QString());
        inletOrder->addItem(QString());
        inletOrder->addItem(QString());
        inletOrder->setObjectName(QString::fromUtf8("inletOrder"));
        inletOrder->setGeometry(QRect(10, 40, 61, 22));
        label_43 = new QLabel(groupBox_11);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(10, 20, 51, 16));
        label_48 = new QLabel(groupBox_11);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(150, 20, 51, 16));
        sourceVelocity2 = new ImprovedLineEdit(groupBox_11);
        sourceVelocity2->setObjectName(QString::fromUtf8("sourceVelocity2"));
        sourceVelocity2->setGeometry(QRect(150, 40, 61, 20));
        label_54 = new QLabel(groupBox_11);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(220, 20, 81, 16));
        sourcePressure = new ImprovedLineEdit(groupBox_11);
        sourcePressure->setObjectName(QString::fromUtf8("sourcePressure"));
        sourcePressure->setGeometry(QRect(220, 40, 61, 20));
        label_77 = new QLabel(groupBox_11);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(290, 20, 81, 16));
        inletFormula = new QLineEdit(groupBox_11);
        inletFormula->setObjectName(QString::fromUtf8("inletFormula"));
        inletFormula->setGeometry(QRect(290, 40, 181, 20));
        groupBox_12 = new QGroupBox(tab_3);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(340, 10, 151, 121));
        label_44 = new QLabel(groupBox_12);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 20, 81, 16));
        movingVelocity = new ImprovedLineEdit(groupBox_12);
        movingVelocity->setObjectName(QString::fromUtf8("movingVelocity"));
        movingVelocity->setGeometry(QRect(10, 40, 61, 20));
        label_46 = new QLabel(groupBox_12);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(10, 70, 81, 16));
        movingVelocityY = new ImprovedLineEdit(groupBox_12);
        movingVelocityY->setObjectName(QString::fromUtf8("movingVelocityY"));
        movingVelocityY->setGeometry(QRect(10, 90, 61, 20));
        movingVelocity2 = new ImprovedLineEdit(groupBox_12);
        movingVelocity2->setObjectName(QString::fromUtf8("movingVelocity2"));
        movingVelocity2->setGeometry(QRect(80, 40, 61, 20));
        movingVelocityY2 = new ImprovedLineEdit(groupBox_12);
        movingVelocityY2->setObjectName(QString::fromUtf8("movingVelocityY2"));
        movingVelocityY2->setGeometry(QRect(80, 90, 61, 20));
        label_41 = new QLabel(groupBox_12);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(80, 20, 46, 13));
        label_42 = new QLabel(groupBox_12);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(80, 70, 46, 13));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        groupBox_2 = new QGroupBox(tab_4);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 10, 291, 71));
        label = new QLabel(groupBox_2);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 46, 13));
        mpG = new ImprovedLineEdit(groupBox_2);
        mpG->setObjectName(QString::fromUtf8("mpG"));
        mpG->setGeometry(QRect(10, 40, 61, 20));
        mpPsi0 = new ImprovedLineEdit(groupBox_2);
        mpPsi0->setObjectName(QString::fromUtf8("mpPsi0"));
        mpPsi0->setGeometry(QRect(80, 40, 61, 20));
        mpP0 = new ImprovedLineEdit(groupBox_2);
        mpP0->setObjectName(QString::fromUtf8("mpP0"));
        mpP0->setGeometry(QRect(150, 40, 61, 20));
        label_2 = new QLabel(groupBox_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(80, 20, 46, 13));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(150, 20, 46, 13));
        label_18 = new QLabel(groupBox_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(220, 20, 46, 13));
        mpGads = new ImprovedLineEdit(groupBox_2);
        mpGads->setObjectName(QString::fromUtf8("mpGads"));
        mpGads->setGeometry(QRect(220, 40, 61, 20));
        groupBox_4 = new QGroupBox(tab_4);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 90, 481, 71));
        mcQuantity = new QComboBox(groupBox_4);
        mcQuantity->addItem(QString());
        mcQuantity->addItem(QString());
        mcQuantity->addItem(QString());
        mcQuantity->setObjectName(QString::fromUtf8("mcQuantity"));
        mcQuantity->setGeometry(QRect(10, 40, 61, 22));
        label_4 = new QLabel(groupBox_4);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 20, 121, 16));
        label_5 = new QLabel(groupBox_4);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(80, 20, 46, 13));
        mcG = new ImprovedLineEdit(groupBox_4);
        mcG->setObjectName(QString::fromUtf8("mcG"));
        mcG->setGeometry(QRect(80, 40, 61, 20));
        label_19 = new QLabel(groupBox_4);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(150, 20, 46, 13));
        mcGads = new ImprovedLineEdit(groupBox_4);
        mcGads->setObjectName(QString::fromUtf8("mcGads"));
        mcGads->setGeometry(QRect(150, 40, 61, 20));
        label_20 = new QLabel(groupBox_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(220, 20, 46, 13));
        mcGads2 = new ImprovedLineEdit(groupBox_4);
        mcGads2->setObjectName(QString::fromUtf8("mcGads2"));
        mcGads2->setGeometry(QRect(220, 40, 61, 20));
        label_21 = new QLabel(groupBox_4);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(290, 20, 46, 13));
        mcType = new QComboBox(groupBox_4);
        mcType->addItem(QString());
        mcType->addItem(QString());
        mcType->addItem(QString());
        mcType->addItem(QString());
        mcType->addItem(QString());
        mcType->setObjectName(QString::fromUtf8("mcType"));
        mcType->setGeometry(QRect(290, 40, 111, 22));
        label_76 = new QLabel(groupBox_4);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(410, 20, 71, 16));
        mcDensityRatio = new ImprovedLineEdit(groupBox_4);
        mcDensityRatio->setObjectName(QString::fromUtf8("mcDensityRatio"));
        mcDensityRatio->setGeometry(QRect(410, 40, 61, 20));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        activateKorner = new QCheckBox(tab_5);
        activateKorner->setObjectName(QString::fromUtf8("activateKorner"));
        activateKorner->setGeometry(QRect(10, 10, 481, 18));
        activateKorner->setChecked(false);
        groupBox_19 = new QGroupBox(tab_5);
        groupBox_19->setObjectName(QString::fromUtf8("groupBox_19"));
        groupBox_19->setGeometry(QRect(10, 40, 471, 71));
        label_65 = new QLabel(groupBox_19);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 20, 101, 16));
        ebmPower = new ImprovedLineEdit(groupBox_19);
        ebmPower->setObjectName(QString::fromUtf8("ebmPower"));
        ebmPower->setGeometry(QRect(10, 40, 61, 20));
        label_66 = new QLabel(groupBox_19);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(80, 20, 81, 16));
        ebmStdDev = new ImprovedLineEdit(groupBox_19);
        ebmStdDev->setObjectName(QString::fromUtf8("ebmStdDev"));
        ebmStdDev->setGeometry(QRect(80, 40, 61, 20));
        label_67 = new QLabel(groupBox_19);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(150, 20, 81, 16));
        label_69 = new QLabel(groupBox_19);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(220, 20, 91, 16));
        label_70 = new QLabel(groupBox_19);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(290, 20, 61, 16));
        ebmStartX = new ImprovedLineEdit(groupBox_19);
        ebmStartX->setObjectName(QString::fromUtf8("ebmStartX"));
        ebmStartX->setGeometry(QRect(150, 40, 61, 20));
        ebmVelocity = new ImprovedLineEdit(groupBox_19);
        ebmVelocity->setObjectName(QString::fromUtf8("ebmVelocity"));
        ebmVelocity->setGeometry(QRect(220, 40, 61, 20));
        ebmTimesteps = new ImprovedLineEdit(groupBox_19);
        ebmTimesteps->setObjectName(QString::fromUtf8("ebmTimesteps"));
        ebmTimesteps->setGeometry(QRect(290, 40, 61, 20));
        ebmAbsorptionCoefficient = new ImprovedLineEdit(groupBox_19);
        ebmAbsorptionCoefficient->setObjectName(QString::fromUtf8("ebmAbsorptionCoefficient"));
        ebmAbsorptionCoefficient->setGeometry(QRect(360, 40, 61, 20));
        label_71 = new QLabel(groupBox_19);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(360, 20, 61, 16));
        groupBox_20 = new QGroupBox(tab_5);
        groupBox_20->setObjectName(QString::fromUtf8("groupBox_20"));
        groupBox_20->setGeometry(QRect(10, 120, 471, 71));
        label_68 = new QLabel(groupBox_20);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(10, 20, 101, 16));
        kornerLiquidTau = new ImprovedLineEdit(groupBox_20);
        kornerLiquidTau->setObjectName(QString::fromUtf8("kornerLiquidTau"));
        kornerLiquidTau->setGeometry(QRect(80, 40, 61, 20));
        label_72 = new QLabel(groupBox_20);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(150, 20, 81, 16));
        kornerSolidTau = new ImprovedLineEdit(groupBox_20);
        kornerSolidTau->setObjectName(QString::fromUtf8("kornerSolidTau"));
        kornerSolidTau->setGeometry(QRect(10, 40, 61, 20));
        kornerGasTau = new ImprovedLineEdit(groupBox_20);
        kornerGasTau->setObjectName(QString::fromUtf8("kornerGasTau"));
        kornerGasTau->setGeometry(QRect(150, 40, 61, 20));
        label_73 = new QLabel(groupBox_20);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(80, 20, 81, 16));
        kornerSolidEnergy = new ImprovedLineEdit(groupBox_20);
        kornerSolidEnergy->setObjectName(QString::fromUtf8("kornerSolidEnergy"));
        kornerSolidEnergy->setGeometry(QRect(220, 40, 61, 20));
        label_74 = new QLabel(groupBox_20);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(220, 20, 81, 16));
        kornerLiquidEnergy = new ImprovedLineEdit(groupBox_20);
        kornerLiquidEnergy->setObjectName(QString::fromUtf8("kornerLiquidEnergy"));
        kornerLiquidEnergy->setGeometry(QRect(290, 40, 61, 20));
        label_75 = new QLabel(groupBox_20);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(290, 20, 81, 16));
        tabWidget->addTab(tab_5, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        label_55 = new QLabel(tab_7);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 10, 81, 16));
        label_55->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        nanoFraction = new ImprovedLineEdit(tab_7);
        nanoFraction->setObjectName(QString::fromUtf8("nanoFraction"));
        nanoFraction->setGeometry(QRect(10, 30, 61, 20));
        nanoDensity = new ImprovedLineEdit(tab_7);
        nanoDensity->setObjectName(QString::fromUtf8("nanoDensity"));
        nanoDensity->setGeometry(QRect(10, 130, 61, 20));
        label_56 = new QLabel(tab_7);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(10, 110, 81, 16));
        label_56->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_57 = new QLabel(tab_7);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(10, 160, 171, 16));
        label_57->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        nanoThermalExpansion = new ImprovedLineEdit(tab_7);
        nanoThermalExpansion->setObjectName(QString::fromUtf8("nanoThermalExpansion"));
        nanoThermalExpansion->setGeometry(QRect(10, 180, 61, 20));
        nanoThermalConductivity = new ImprovedLineEdit(tab_7);
        nanoThermalConductivity->setObjectName(QString::fromUtf8("nanoThermalConductivity"));
        nanoThermalConductivity->setGeometry(QRect(10, 230, 61, 20));
        label_58 = new QLabel(tab_7);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 210, 171, 16));
        label_58->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_59 = new QLabel(tab_7);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(10, 260, 171, 16));
        label_59->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        nanoHeatCapacitance = new ImprovedLineEdit(tab_7);
        nanoHeatCapacitance->setObjectName(QString::fromUtf8("nanoHeatCapacitance"));
        nanoHeatCapacitance->setGeometry(QRect(10, 280, 61, 20));
        label_60 = new QLabel(tab_7);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(10, 60, 201, 16));
        nanoparticles = new QComboBox(tab_7);
        nanoparticles->addItem(QString());
        nanoparticles->addItem(QString());
        nanoparticles->addItem(QString());
        nanoparticles->addItem(QString());
        nanoparticles->addItem(QString());
        nanoparticles->setObjectName(QString::fromUtf8("nanoparticles"));
        nanoparticles->setGeometry(QRect(10, 80, 121, 22));
        tabWidget->addTab(tab_7, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        groupBox_5 = new QGroupBox(tab_6);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 10, 151, 71));
        gravityEnable = new QCheckBox(groupBox_5);
        gravityEnable->setObjectName(QString::fromUtf8("gravityEnable"));
        gravityEnable->setGeometry(QRect(10, 20, 71, 18));
        gravity = new ImprovedLineEdit(groupBox_5);
        gravity->setObjectName(QString::fromUtf8("gravity"));
        gravity->setEnabled(false);
        gravity->setGeometry(QRect(10, 40, 61, 20));
        groupBox_6 = new QGroupBox(tab_6);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 90, 151, 71));
        label_23 = new QLabel(groupBox_6);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 20, 46, 13));
        shallowG = new ImprovedLineEdit(groupBox_6);
        shallowG->setObjectName(QString::fromUtf8("shallowG"));
        shallowG->setGeometry(QRect(10, 40, 61, 20));
        label_24 = new QLabel(groupBox_6);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(80, 20, 46, 13));
        shallowNB = new ImprovedLineEdit(groupBox_6);
        shallowNB->setObjectName(QString::fromUtf8("shallowNB"));
        shallowNB->setGeometry(QRect(80, 40, 61, 20));
        groupBox_7 = new QGroupBox(tab_6);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(330, 10, 151, 71));
        porousSolidDensity = new ImprovedLineEdit(groupBox_7);
        porousSolidDensity->setObjectName(QString::fromUtf8("porousSolidDensity"));
        porousSolidDensity->setGeometry(QRect(10, 40, 61, 20));
        label_25 = new QLabel(groupBox_7);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 20, 171, 20));
        label_61 = new QLabel(groupBox_7);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(80, 20, 111, 20));
        porousVariation = new ImprovedLineEdit(groupBox_7);
        porousVariation->setObjectName(QString::fromUtf8("porousVariation"));
        porousVariation->setGeometry(QRect(80, 40, 61, 20));
        groupBox_9 = new QGroupBox(tab_6);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(170, 90, 151, 71));
        label_31 = new QLabel(groupBox_9);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 20, 61, 16));
        depositionRate = new ImprovedLineEdit(groupBox_9);
        depositionRate->setObjectName(QString::fromUtf8("depositionRate"));
        depositionRate->setGeometry(QRect(10, 40, 61, 20));
        groupBox_13 = new QGroupBox(tab_6);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(170, 10, 151, 71));
        label_47 = new QLabel(groupBox_13);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(10, 20, 111, 16));
        slipCoefficient = new ImprovedLineEdit(groupBox_13);
        slipCoefficient->setObjectName(QString::fromUtf8("slipCoefficient"));
        slipCoefficient->setGeometry(QRect(10, 40, 61, 20));
        groupBox_15 = new QGroupBox(tab_6);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(330, 90, 151, 71));
        label_37 = new QLabel(groupBox_15);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(10, 20, 46, 13));
        anodeCathodeFactor = new ImprovedLineEdit(groupBox_15);
        anodeCathodeFactor->setObjectName(QString::fromUtf8("anodeCathodeFactor"));
        anodeCathodeFactor->setGeometry(QRect(10, 40, 61, 20));
        groupBox_16 = new QGroupBox(tab_6);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(10, 170, 311, 121));
        label_45 = new QLabel(groupBox_16);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 20, 131, 16));
        externalForceStrengthX = new ImprovedLineEdit(groupBox_16);
        externalForceStrengthX->setObjectName(QString::fromUtf8("externalForceStrengthX"));
        externalForceStrengthX->setGeometry(QRect(10, 40, 61, 20));
        label_49 = new QLabel(groupBox_16);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(150, 20, 61, 16));
        externalForceMinX = new ImprovedLineEdit(groupBox_16);
        externalForceMinX->setObjectName(QString::fromUtf8("externalForceMinX"));
        externalForceMinX->setGeometry(QRect(150, 40, 61, 20));
        label_50 = new QLabel(groupBox_16);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(220, 20, 61, 16));
        externalForceMaxX = new ImprovedLineEdit(groupBox_16);
        externalForceMaxX->setObjectName(QString::fromUtf8("externalForceMaxX"));
        externalForceMaxX->setGeometry(QRect(220, 40, 61, 20));
        label_51 = new QLabel(groupBox_16);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 70, 61, 16));
        externalForceMinY = new ImprovedLineEdit(groupBox_16);
        externalForceMinY->setObjectName(QString::fromUtf8("externalForceMinY"));
        externalForceMinY->setGeometry(QRect(10, 90, 61, 20));
        label_52 = new QLabel(groupBox_16);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(80, 70, 61, 16));
        externalForceMaxY = new ImprovedLineEdit(groupBox_16);
        externalForceMaxY->setObjectName(QString::fromUtf8("externalForceMaxY"));
        externalForceMaxY->setGeometry(QRect(80, 90, 61, 20));
        externalForceStrengthY = new ImprovedLineEdit(groupBox_16);
        externalForceStrengthY->setObjectName(QString::fromUtf8("externalForceStrengthY"));
        externalForceStrengthY->setGeometry(QRect(80, 40, 61, 20));
        externalForcePeriod = new ImprovedLineEdit(groupBox_16);
        externalForcePeriod->setObjectName(QString::fromUtf8("externalForcePeriod"));
        externalForcePeriod->setGeometry(QRect(150, 90, 61, 20));
        label_53 = new QLabel(groupBox_16);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(150, 70, 61, 16));
        groupBox_18 = new QGroupBox(tab_6);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(330, 170, 151, 121));
        entropic = new QCheckBox(groupBox_18);
        entropic->setObjectName(QString::fromUtf8("entropic"));
        entropic->setGeometry(QRect(10, 70, 71, 18));
        label_26 = new QLabel(groupBox_18);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 20, 171, 16));
        smagorinsky = new ImprovedLineEdit(groupBox_18);
        smagorinsky->setObjectName(QString::fromUtf8("smagorinsky"));
        smagorinsky->setGeometry(QRect(10, 40, 61, 20));
        tabWidget->addTab(tab_6, QString());
        QWidget::setTabOrder(tabWidget, regionAll);
        QWidget::setTabOrder(regionAll, regionCenter);
        QWidget::setTabOrder(regionCenter, minX);
        QWidget::setTabOrder(minX, maxX);
        QWidget::setTabOrder(maxX, minY);
        QWidget::setTabOrder(minY, maxY);
        QWidget::setTabOrder(maxY, minZ);
        QWidget::setTabOrder(minZ, maxZ);
        QWidget::setTabOrder(maxZ, density1);
        QWidget::setTabOrder(density1, density2);
        QWidget::setTabOrder(density2, updateInitial);
        QWidget::setTabOrder(updateInitial, updateConstant);
        QWidget::setTabOrder(updateConstant, minP0);
        QWidget::setTabOrder(minP0, maxP0);
        QWidget::setTabOrder(maxP0, colorComponentPorous);
        QWidget::setTabOrder(colorComponentPorous, averageValuePorous);
        QWidget::setTabOrder(averageValuePorous, variationPorous);
        QWidget::setTabOrder(variationPorous, loadMaskPorousMedia);
        QWidget::setTabOrder(loadMaskPorousMedia, dx);
        QWidget::setTabOrder(dx, dm);
        QWidget::setTabOrder(dm, fluidOrder);
        QWidget::setTabOrder(fluidOrder, material);
        QWidget::setTabOrder(material, velocityOrder);
        QWidget::setTabOrder(velocityOrder, periodicBoundaries);
        QWidget::setTabOrder(periodicBoundaries, outletStrategy);
        QWidget::setTabOrder(outletStrategy, inletOrder);
        QWidget::setTabOrder(inletOrder, sourceVelocity);
        QWidget::setTabOrder(sourceVelocity, sourceVelocity2);
        QWidget::setTabOrder(sourceVelocity2, sourcePressure);
        QWidget::setTabOrder(sourcePressure, thermalGravity);
        QWidget::setTabOrder(thermalGravity, thermalExpansion);
        QWidget::setTabOrder(thermalExpansion, thermalIndex);
        QWidget::setTabOrder(thermalIndex, thermal1);
        QWidget::setTabOrder(thermal1, movingVelocity);
        QWidget::setTabOrder(movingVelocity, movingVelocityY);
        QWidget::setTabOrder(movingVelocityY, movingVelocity2);
        QWidget::setTabOrder(movingVelocity2, movingVelocityY2);
        QWidget::setTabOrder(movingVelocityY2, mpG);
        QWidget::setTabOrder(mpG, mpPsi0);
        QWidget::setTabOrder(mpPsi0, mpP0);
        QWidget::setTabOrder(mpP0, mpGads);
        QWidget::setTabOrder(mpGads, mcQuantity);
        QWidget::setTabOrder(mcQuantity, mcG);
        QWidget::setTabOrder(mcG, mcGads);
        QWidget::setTabOrder(mcGads, mcGads2);
        QWidget::setTabOrder(mcGads2, mcType);
        QWidget::setTabOrder(mcType, nanoFraction);
        QWidget::setTabOrder(nanoFraction, nanoparticles);
        QWidget::setTabOrder(nanoparticles, nanoDensity);
        QWidget::setTabOrder(nanoDensity, nanoThermalExpansion);
        QWidget::setTabOrder(nanoThermalExpansion, nanoThermalConductivity);
        QWidget::setTabOrder(nanoThermalConductivity, nanoHeatCapacitance);
        QWidget::setTabOrder(nanoHeatCapacitance, gravityEnable);
        QWidget::setTabOrder(gravityEnable, gravity);
        QWidget::setTabOrder(gravity, slipCoefficient);
        QWidget::setTabOrder(slipCoefficient, porousSolidDensity);
        QWidget::setTabOrder(porousSolidDensity, porousVariation);
        QWidget::setTabOrder(porousVariation, shallowG);
        QWidget::setTabOrder(shallowG, shallowNB);
        QWidget::setTabOrder(shallowNB, depositionRate);
        QWidget::setTabOrder(depositionRate, anodeCathodeFactor);
        QWidget::setTabOrder(anodeCathodeFactor, externalForceStrengthX);
        QWidget::setTabOrder(externalForceStrengthX, externalForceStrengthY);
        QWidget::setTabOrder(externalForceStrengthY, externalForceMinX);
        QWidget::setTabOrder(externalForceMinX, externalForceMaxX);
        QWidget::setTabOrder(externalForceMaxX, externalForceMinY);
        QWidget::setTabOrder(externalForceMinY, externalForceMaxY);
        QWidget::setTabOrder(externalForceMaxY, externalForcePeriod);
        QWidget::setTabOrder(externalForcePeriod, epsilon);
        QWidget::setTabOrder(epsilon, kinematicViscosity);
        QWidget::setTabOrder(kinematicViscosity, model);

        retranslateUi(Parameters2);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(Parameters2);
    } // setupUi

    void retranslateUi(QDialog *Parameters2)
    {
        Parameters2->setWindowTitle(QCoreApplication::translate("Parameters2", "Parameters", nullptr));
        model->setItemText(0, QCoreApplication::translate("Parameters2", "D2Q9", nullptr));
        model->setItemText(1, QCoreApplication::translate("Parameters2", "D3Q15", nullptr));
        model->setItemText(2, QCoreApplication::translate("Parameters2", "D3Q19", nullptr));
        model->setItemText(3, QCoreApplication::translate("Parameters2", "D3Q27", nullptr));

        label_6->setText(QCoreApplication::translate("Parameters2", "Model:", nullptr));
        label_22->setText(QCoreApplication::translate("Parameters2", "Velocity Order:", nullptr));
        velocityOrder->setText(QCoreApplication::translate("Parameters2", "2", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("Parameters2", "Main Parameters", nullptr));
        dm->setText(QCoreApplication::translate("Parameters2", "8e-18", nullptr));
        dx->setText(QCoreApplication::translate("Parameters2", "1e-6", nullptr));
        label_29->setText(QCoreApplication::translate("Parameters2", "dx (m):", nullptr));
        label_30->setText(QCoreApplication::translate("Parameters2", "dt (s):", nullptr));
        label_28->setText(QCoreApplication::translate("Parameters2", "dm (Kg):", nullptr));
        dt->setText(QCoreApplication::translate("Parameters2", "0.167e-6", nullptr));
        groupBox_14->setTitle(QCoreApplication::translate("Parameters2", "Fluids", nullptr));
        label_27->setText(QCoreApplication::translate("Parameters2", "Material:", nullptr));
        label_13->setText(QCoreApplication::translate("Parameters2", "K. Viscosity (m^2/s):", nullptr));
        material->setItemText(0, QCoreApplication::translate("Parameters2", "Other", nullptr));
        material->setItemText(1, QCoreApplication::translate("Parameters2", "Water 20C", nullptr));
        material->setItemText(2, QCoreApplication::translate("Parameters2", "Air 25C", nullptr));
        material->setItemText(3, QCoreApplication::translate("Parameters2", "Kerosene 20C", nullptr));

#if QT_CONFIG(tooltip)
        epsilon->setToolTip(QCoreApplication::translate("Parameters2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Relaxation parameter of the BGK approximation.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">It must be greater than 0.5 (and not so close to this value).</span></p></body></html>", nullptr));
#endif // QT_CONFIG(tooltip)
        epsilon->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_32->setText(QCoreApplication::translate("Parameters2", "Epsilon:", nullptr));
        kinematicViscosity->setText(QCoreApplication::translate("Parameters2", "1e-6", nullptr));
        label_40->setText(QCoreApplication::translate("Parameters2", "Order:", nullptr));
        fluidOrder->setItemText(0, QCoreApplication::translate("Parameters2", "1st", nullptr));
        fluidOrder->setItemText(1, QCoreApplication::translate("Parameters2", "2nd", nullptr));

        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("Parameters2", "Model", nullptr));
        groupBox->setTitle(QCoreApplication::translate("Parameters2", "By region", nullptr));
        updateInitial->setText(QCoreApplication::translate("Parameters2", "Initial", nullptr));
        label_11->setText(QCoreApplication::translate("Parameters2", "Max Y:", nullptr));
        label_8->setText(QCoreApplication::translate("Parameters2", "Max X:", nullptr));
        label_14->setText(QCoreApplication::translate("Parameters2", "Density 1:", nullptr));
        label_15->setText(QCoreApplication::translate("Parameters2", "Density 2:", nullptr));
        label_10->setText(QCoreApplication::translate("Parameters2", "Min Z:", nullptr));
        label_7->setText(QCoreApplication::translate("Parameters2", "Max Z:", nullptr));
        label_9->setText(QCoreApplication::translate("Parameters2", "Min X:", nullptr));
        label_12->setText(QCoreApplication::translate("Parameters2", "Min Y:", nullptr));
        updateConstant->setText(QCoreApplication::translate("Parameters2", "Constant", nullptr));
        regionAll->setText(QCoreApplication::translate("Parameters2", "All", nullptr));
        regionCenter->setText(QCoreApplication::translate("Parameters2", "Center", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("Parameters2", "Global", nullptr));
        label_16->setText(QCoreApplication::translate("Parameters2", "min:", nullptr));
        minP0->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_17->setText(QCoreApplication::translate("Parameters2", "max:", nullptr));
        maxP0->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        groupBox_17->setTitle(QCoreApplication::translate("Parameters2", "Porous Media", nullptr));
        loadMaskPorousMedia->setText(QCoreApplication::translate("Parameters2", "Load Mask", nullptr));
        label_62->setText(QCoreApplication::translate("Parameters2", "Color Component:", nullptr));
        colorComponentPorous->setItemText(0, QCoreApplication::translate("Parameters2", "RGB - R", nullptr));
        colorComponentPorous->setItemText(1, QCoreApplication::translate("Parameters2", "RGB - G", nullptr));
        colorComponentPorous->setItemText(2, QCoreApplication::translate("Parameters2", "RGB - B", nullptr));
        colorComponentPorous->setItemText(3, QCoreApplication::translate("Parameters2", "HSV - H", nullptr));
        colorComponentPorous->setItemText(4, QCoreApplication::translate("Parameters2", "HSV - S", nullptr));
        colorComponentPorous->setItemText(5, QCoreApplication::translate("Parameters2", "HSV - V", nullptr));
        colorComponentPorous->setItemText(6, QCoreApplication::translate("Parameters2", "CMYK - C", nullptr));
        colorComponentPorous->setItemText(7, QCoreApplication::translate("Parameters2", "CMYK - M", nullptr));
        colorComponentPorous->setItemText(8, QCoreApplication::translate("Parameters2", "CMYK - Y", nullptr));
        colorComponentPorous->setItemText(9, QCoreApplication::translate("Parameters2", "CMYK - K", nullptr));

        label_63->setText(QCoreApplication::translate("Parameters2", "Average Value:", nullptr));
        averageValuePorous->setText(QCoreApplication::translate("Parameters2", "0.5", nullptr));
        label_64->setText(QCoreApplication::translate("Parameters2", "Variation:", nullptr));
        variationPorous->setText(QCoreApplication::translate("Parameters2", "0.5", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("Parameters2", "Initial", nullptr));
        periodicBoundaries->setText(QCoreApplication::translate("Parameters2", "Periodic Boundaries", nullptr));
        label_33->setText(QCoreApplication::translate("Parameters2", "Strategy:", nullptr));
        outletStrategy->setItemText(0, QCoreApplication::translate("Parameters2", "---", nullptr));
        outletStrategy->setItemText(1, QCoreApplication::translate("Parameters2", "Equilibrium", nullptr));
        outletStrategy->setItemText(2, QCoreApplication::translate("Parameters2", "Fixed flux", nullptr));
        outletStrategy->setItemText(3, QCoreApplication::translate("Parameters2", "Zou and He", nullptr));

        groupBox_10->setTitle(QCoreApplication::translate("Parameters2", "Thermal Walls", nullptr));
        thermal1->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_34->setText(QCoreApplication::translate("Parameters2", "Temperature:", nullptr));
        thermalGravity->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_36->setText(QCoreApplication::translate("Parameters2", "Gravity:", nullptr));
        label_38->setText(QCoreApplication::translate("Parameters2", "TEC:", nullptr));
        thermalExpansion->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_35->setText(QCoreApplication::translate("Parameters2", "Order:", nullptr));
        thermalIndex->setItemText(0, QCoreApplication::translate("Parameters2", "1st", nullptr));
        thermalIndex->setItemText(1, QCoreApplication::translate("Parameters2", "2nd", nullptr));
        thermalIndex->setItemText(2, QCoreApplication::translate("Parameters2", "3rd", nullptr));

        groupBox_11->setTitle(QCoreApplication::translate("Parameters2", "Inlets", nullptr));
#if QT_CONFIG(tooltip)
        sourceVelocity->setToolTip(QCoreApplication::translate("Parameters2", "The nondimentional value of velocity in LB should be limited to 0.1\n"
"(according to Sukop's recomendation), due to the incompressibility assumption.", nullptr));
#endif // QT_CONFIG(tooltip)
        sourceVelocity->setText(QCoreApplication::translate("Parameters2", "0.02", nullptr));
        label_39->setText(QCoreApplication::translate("Parameters2", "Velocity:", nullptr));
        inletOrder->setItemText(0, QCoreApplication::translate("Parameters2", "1st", nullptr));
        inletOrder->setItemText(1, QCoreApplication::translate("Parameters2", "2nd", nullptr));
        inletOrder->setItemText(2, QCoreApplication::translate("Parameters2", "3rd", nullptr));

        label_43->setText(QCoreApplication::translate("Parameters2", "Order:", nullptr));
        label_48->setText(QCoreApplication::translate("Parameters2", "m/s:", nullptr));
        sourceVelocity2->setText(QCoreApplication::translate("Parameters2", "0.02", nullptr));
        label_54->setText(QCoreApplication::translate("Parameters2", "Pressure:", nullptr));
#if QT_CONFIG(tooltip)
        sourcePressure->setToolTip(QCoreApplication::translate("Parameters2", "The nondimentional value of velocity in LB should be limited to 0.1\n"
"(according to Sukop's recomendation), due to the incompressibility assumption.", nullptr));
#endif // QT_CONFIG(tooltip)
        sourcePressure->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_77->setText(QCoreApplication::translate("Parameters2", "Formula:", nullptr));
        groupBox_12->setTitle(QCoreApplication::translate("Parameters2", "Moving Walls", nullptr));
        label_44->setText(QCoreApplication::translate("Parameters2", "Velocity X:", nullptr));
#if QT_CONFIG(tooltip)
        movingVelocity->setToolTip(QCoreApplication::translate("Parameters2", "The nondimentional value of velocity in LB should be limited to 0.1\n"
"(according to Sukop's recomendation), due to the incompressibility assumption.", nullptr));
#endif // QT_CONFIG(tooltip)
        movingVelocity->setText(QCoreApplication::translate("Parameters2", "0.02", nullptr));
        label_46->setText(QCoreApplication::translate("Parameters2", "Velocity Y:", nullptr));
#if QT_CONFIG(tooltip)
        movingVelocityY->setToolTip(QCoreApplication::translate("Parameters2", "The nondimentional value of velocity in LB should be limited to 0.1\n"
"(according to Sukop's recomendation), due to the incompressibility assumption.", nullptr));
#endif // QT_CONFIG(tooltip)
        movingVelocityY->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        movingVelocity2->setText(QCoreApplication::translate("Parameters2", "0.02", nullptr));
        movingVelocityY2->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_41->setText(QCoreApplication::translate("Parameters2", "m/s:", nullptr));
        label_42->setText(QCoreApplication::translate("Parameters2", "m/s:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("Parameters2", "Boundary", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("Parameters2", "MultiPhase", nullptr));
        label->setText(QCoreApplication::translate("Parameters2", "G:", nullptr));
        mpG->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        mpPsi0->setText(QCoreApplication::translate("Parameters2", "4", nullptr));
        mpP0->setText(QCoreApplication::translate("Parameters2", "200", nullptr));
        label_2->setText(QCoreApplication::translate("Parameters2", "Psi0:", nullptr));
        label_3->setText(QCoreApplication::translate("Parameters2", "P0:", nullptr));
        label_18->setText(QCoreApplication::translate("Parameters2", "Gads:", nullptr));
        mpGads->setText(QCoreApplication::translate("Parameters2", "-190", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("Parameters2", "MultiComponent", nullptr));
        mcQuantity->setItemText(0, QCoreApplication::translate("Parameters2", "1", nullptr));
        mcQuantity->setItemText(1, QCoreApplication::translate("Parameters2", "2", nullptr));
        mcQuantity->setItemText(2, QCoreApplication::translate("Parameters2", "3", nullptr));

        label_4->setText(QCoreApplication::translate("Parameters2", "Comps:", nullptr));
        label_5->setText(QCoreApplication::translate("Parameters2", "G:", nullptr));
        mcG->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_19->setText(QCoreApplication::translate("Parameters2", "Gads 1:", nullptr));
        mcGads->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_20->setText(QCoreApplication::translate("Parameters2", "Gads 2:", nullptr));
        mcGads2->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_21->setText(QCoreApplication::translate("Parameters2", "Impl:", nullptr));
        mcType->setItemText(0, QCoreApplication::translate("Parameters2", "SC", nullptr));
        mcType->setItemText(1, QCoreApplication::translate("Parameters2", "RK", nullptr));
        mcType->setItemText(2, QCoreApplication::translate("Parameters2", "FE", nullptr));
        mcType->setItemText(3, QCoreApplication::translate("Parameters2", "PS", nullptr));
        mcType->setItemText(4, QCoreApplication::translate("Parameters2", "Deposition", nullptr));

        label_76->setText(QCoreApplication::translate("Parameters2", "Dens. Ratio:", nullptr));
        mcDensityRatio->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QCoreApplication::translate("Parameters2", "MP / MC", nullptr));
        activateKorner->setText(QCoreApplication::translate("Parameters2", "Activate Korner's implementation", nullptr));
        groupBox_19->setTitle(QCoreApplication::translate("Parameters2", "Electron Beam Gun", nullptr));
        label_65->setText(QCoreApplication::translate("Parameters2", "Power:", nullptr));
        ebmPower->setText(QCoreApplication::translate("Parameters2", "0.5", nullptr));
        label_66->setText(QCoreApplication::translate("Parameters2", "Std. Dev.:", nullptr));
        ebmStdDev->setText(QCoreApplication::translate("Parameters2", "0.1", nullptr));
        label_67->setText(QCoreApplication::translate("Parameters2", "Start X:", nullptr));
        label_69->setText(QCoreApplication::translate("Parameters2", "Velocity:", nullptr));
        label_70->setText(QCoreApplication::translate("Parameters2", "Timesteps:", nullptr));
        ebmStartX->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        ebmVelocity->setText(QCoreApplication::translate("Parameters2", "0.01", nullptr));
        ebmTimesteps->setText(QCoreApplication::translate("Parameters2", "10000", nullptr));
        ebmAbsorptionCoefficient->setText(QCoreApplication::translate("Parameters2", "0.5", nullptr));
        label_71->setText(QCoreApplication::translate("Parameters2", "Absorption:", nullptr));
        groupBox_20->setTitle(QCoreApplication::translate("Parameters2", "Thermal Properties", nullptr));
        label_68->setText(QCoreApplication::translate("Parameters2", "Solid Tau:", nullptr));
        kornerLiquidTau->setText(QCoreApplication::translate("Parameters2", "0.7", nullptr));
        label_72->setText(QCoreApplication::translate("Parameters2", "Gas Tau:", nullptr));
        kornerSolidTau->setText(QCoreApplication::translate("Parameters2", "0.65", nullptr));
        kornerGasTau->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_73->setText(QCoreApplication::translate("Parameters2", "Liquid Tau:", nullptr));
        kornerSolidEnergy->setText(QCoreApplication::translate("Parameters2", "1.5", nullptr));
        label_74->setText(QCoreApplication::translate("Parameters2", "Solid Energy:", nullptr));
        kornerLiquidEnergy->setText(QCoreApplication::translate("Parameters2", "2", nullptr));
        label_75->setText(QCoreApplication::translate("Parameters2", "Liquid Energy:", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QCoreApplication::translate("Parameters2", "Phase Change", nullptr));
        label_55->setText(QCoreApplication::translate("Parameters2", "Solid Fraction:", nullptr));
        nanoFraction->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        nanoDensity->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_56->setText(QCoreApplication::translate("Parameters2", "Relative Density:", nullptr));
        label_57->setText(QCoreApplication::translate("Parameters2", "Relative Thermal Expansion:", nullptr));
        nanoThermalExpansion->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        nanoThermalConductivity->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_58->setText(QCoreApplication::translate("Parameters2", "Relative Thermal Conductivity:", nullptr));
        label_59->setText(QCoreApplication::translate("Parameters2", "Relative Heat Capacitance:", nullptr));
        nanoHeatCapacitance->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_60->setText(QCoreApplication::translate("Parameters2", "Nanoparticles:", nullptr));
        nanoparticles->setItemText(0, QCoreApplication::translate("Parameters2", "None", nullptr));
        nanoparticles->setItemText(1, QCoreApplication::translate("Parameters2", "Ag", nullptr));
        nanoparticles->setItemText(2, QCoreApplication::translate("Parameters2", "Al2O3", nullptr));
        nanoparticles->setItemText(3, QCoreApplication::translate("Parameters2", "Cu", nullptr));
        nanoparticles->setItemText(4, QCoreApplication::translate("Parameters2", "TiO2", nullptr));

        tabWidget->setTabText(tabWidget->indexOf(tab_7), QCoreApplication::translate("Parameters2", "Nanofluid", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("Parameters2", "Gravity", nullptr));
        gravityEnable->setText(QCoreApplication::translate("Parameters2", "Gravity", nullptr));
        gravity->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("Parameters2", "Shallow Water", nullptr));
        label_23->setText(QCoreApplication::translate("Parameters2", "G:", nullptr));
        shallowG->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        label_24->setText(QCoreApplication::translate("Parameters2", "NB:", nullptr));
        shallowNB->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("Parameters2", "Sukop's Porous", nullptr));
        porousSolidDensity->setText(QCoreApplication::translate("Parameters2", "0.5", nullptr));
        label_25->setText(QCoreApplication::translate("Parameters2", "Solid Density:", nullptr));
        label_61->setText(QCoreApplication::translate("Parameters2", "Variation:", nullptr));
        porousVariation->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        groupBox_9->setTitle(QCoreApplication::translate("Parameters2", "Deposition", nullptr));
        label_31->setText(QCoreApplication::translate("Parameters2", "Rate:", nullptr));
        depositionRate->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        groupBox_13->setTitle(QCoreApplication::translate("Parameters2", "Partial Slip Wall", nullptr));
        label_47->setText(QCoreApplication::translate("Parameters2", "Slip Coefficient:", nullptr));
        slipCoefficient->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        groupBox_15->setTitle(QCoreApplication::translate("Parameters2", "Anode / Cathode", nullptr));
        label_37->setText(QCoreApplication::translate("Parameters2", "Factor:", nullptr));
        anodeCathodeFactor->setText(QCoreApplication::translate("Parameters2", "1", nullptr));
        groupBox_16->setTitle(QCoreApplication::translate("Parameters2", "External Force", nullptr));
        label_45->setText(QCoreApplication::translate("Parameters2", "Strength (x, y):", nullptr));
        externalForceStrengthX->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_49->setText(QCoreApplication::translate("Parameters2", "Min X:", nullptr));
        externalForceMinX->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_50->setText(QCoreApplication::translate("Parameters2", "Max X:", nullptr));
        externalForceMaxX->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_51->setText(QCoreApplication::translate("Parameters2", "Min Y:", nullptr));
        externalForceMinY->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_52->setText(QCoreApplication::translate("Parameters2", "Max Y:", nullptr));
        externalForceMaxY->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        externalForceStrengthY->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        externalForcePeriod->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        label_53->setText(QCoreApplication::translate("Parameters2", "Period:", nullptr));
        groupBox_18->setTitle(QCoreApplication::translate("Parameters2", "Turbulence", nullptr));
        entropic->setText(QCoreApplication::translate("Parameters2", "Entropic", nullptr));
        label_26->setText(QCoreApplication::translate("Parameters2", "Smagorinsky:", nullptr));
        smagorinsky->setText(QCoreApplication::translate("Parameters2", "0", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QCoreApplication::translate("Parameters2", "Other", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Parameters2: public Ui_Parameters2 {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PARAMETERS2_H
